// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agqjratcydfvacjnlfav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncWpyYXRjeWRmdmFjam5sZmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyOTQ4MjMsImV4cCI6MjA1MTg3MDgyM30.0FgreKRycN-tajIlq9qgpfdCp_RCqFI3wGs5AThAzIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);